spring.application.name=InplayEvents

spring.thymeleaf.cache=false

spring.datasource.url=jdbc:mariadb://localhost:3307/club_padel
spring.datasource.username={User DB}
spring.datasource.password= {Password DB}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
