spring.application.name=InplayEvents

spring.datasource.url=jdbc:mariadb://inplay-mariadb:3306/club_padel
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


spring.datasource.hikari.connectionInitSql=SET NAMES utf8mb4
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.validationTimeout=5000



